export const skillData = {
  languages: ["JS/TS", "Dart", "Python3", "Java", "C/C++"],
  frameworks: [
    "Node.js",
    "Next.js",
    "Express.js",
    "Flutter",
    "Android",
    "TailwindCSS",
    "Prisma",
  ],
  databases: ["PostgreSQL", "SQLite3", "MySQL", "MongoDB"],
  tools: ["Git/GitHub", "Nix", "Vercel", "Planetscale", "Framer Motion"],
  os: [
    "Linux", // i use arch/nixos btw
    "Windows",
  ],
};

export const projectsData = {
  data: [
    {
      name: "ModelCraft",
      description: "Online Model Training",
      link: "https://github.com/cryskram/algopred",
      image: "/projects/modelcraft.png",
      tags: ["Website", "ML", "Full Stack"],
    },
    {
      name: "Algorithm Sorting Visualiser",
      description: "A visual representation of sorting algorithms",
      link: "https://github.com/cryskram/sortingalgo",
      image: "/projects/asv.png",
      tags: ["Website", "Algorithms"],
    },
    {
      name: "Attendance Portal",
      description: "A Simple Attendance Portal for peer learning session demo",
      link: "https://github.com/cryskram/webdevpeersesh",
      image: "/projects/attendance.png",
      tags: ["Website", "Learning", "Full Stack"],
    },
    {
      name: "DropConnect",
      description: "A social media website",
      link: "https://github.com/cryskram/dropconnect",
      image: "/projects/dropconnect.png",
      tags: ["Website", "Social Media"],
    },
    {
      name: "Nrittam",
      description: "Frontend for an AI powered dancing assistant",
      link: "https://github.com/cryskram/nrittam",
      image: "/projects/nrittam.jpeg",
      tags: ["Mobile", "Tutor", "Frontend"],
    },
    {
      name: "Portfolio",
      description: "This website :)",
      link: "https://github.com/cryskram/portfolio",
      image: "/projects/portfolio.png",
      tags: ["Website", "Portfolio"],
    },
    {
      name: "BitPlays",
      description: "Mini games",
      link: "https://github.com/cryskram/bitplays",
      image: "/projects/bitplays.png",
      tags: ["Website", "Game"],
    },
    {
      name: "Todoism",
      description: "End-to-end secure todo manager",
      link: "https://github.com/cryskram/todoism",
      image: "/projects/todoism.png",
      tags: ["Website", "Utility"],
    },
    {
      name: "Quizo",
      description: "A simple Quiz",
      link: "https://github.com/cryskram/quizo",
      image: "/projects/quizo.png",
      tags: ["Website", "Game"],
    },
    {
      name: "SPS Day Celebration",
      description: "A simple frontend website for SPS day celebration",
      link: "https://github.com/cryskram/spsdaycelebration",
      image: "/projects/sps.png",
      tags: ["Website", "Frontend"],
    },
    {
      name: "CyberSpiders",
      description: "A hackernews aggregator for codejam",
      link: "https://github.com/CyberSpiders/cyberspider",
      image: "/projects/cyberspider.png",
      tags: ["Website"],
    },
    {
      name: "DiscoGen",
      description: "A Discord Bot generator",
      link: "https://github.com/https://github.com/Discogen/discogen/cyberspider",
      image: "/projects/discogenImg.png",
      tags: ["Utility", "Software"],
    },
    {
      name: "UGuess",
      description: "Guess the number game",
      link: "https://github.com/cryskram/uguess",
      image: "/projects/uguess.png",
      tags: ["Mobile App", "Game"],
    },
    {
      name: "Bilobe Language",
      description: "A simple toy programming language",
      link: "https://github.com/cryskram/Bilobe",
      image: "/projects/bilobe.png",
      tags: ["Software"],
    },
  ],
};
